---
name: PortalApplicationReadFilter
version: 0
class: com.vordel.circuit.apiportal.ReadApplicationFilter
fields:
  idSelector:
    type: string
    defaultValues:
    - data: ${apimgmt.application.id}
    cardinality: 1
  targetAttribute:
    type: string
    defaultValues:
    - data: apimgmt.application
    cardinality: 1
