---
name: NonceCacheConfiguration
version: 1
class: com.vordel.security.auth.NonceUtility
fields:
  clearCacheIfFull:
    type: boolean
    defaultValues:
    - data: 0
    cardinality: 1
  httpNonceMaxCacheSize:
    type: integer
    defaultValues:
    - data: 500
    cardinality: 1
  wsNonceMaxCacheSize:
    type: integer
    defaultValues:
    - data: 100
    cardinality: 1
  wsNonceTimestampMaxCacheSize:
    type: integer
    defaultValues:
    - data: 1000
    cardinality: 1
