---
type: SophosConfigSet
fields:
  name: Win32 Default Settings
children:
- type: SophosNameValue
  fields:
    name: Access
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: ScrapObjectHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: PECompact
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: OF95DecryptHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: GrpInternet
    type: 9
    value: 2
- type: SophosNameValue
  fields:
    name: MimeEmbedLimit
    type: 2
    value: 25
- type: SophosNameValue
  fields:
    name: ZipDecompression
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: GrpMisc
    type: 9
    value: 2
- type: SophosNameValue
  fields:
    name: Mime
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: MSCompress
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: DynamicDecompression
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: CleanJpeg
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: IdeDir
    type: 10
    value: .
- type: SophosNameValue
  fields:
    name: Emulation
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: MaxRecursionDepth
    type: 2
    value: 16
- type: SophosNameValue
  fields:
    name: FullSweep
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: ProjectHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: ActiveMimeHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: EnableAutoStop
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: VbaOnly
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: PEHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: CleanMp3
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Pdf
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: ConcatenatedArchives
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: DecompressVBA5
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: TarDecompression
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: VbFiltering
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: OleRawHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: StorageReportAll
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: ExecFileDisinfection
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: UnixArchive
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Ole2FileDisinfection
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: ASPack
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: PalmPilotHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: MbinDecompression
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: VbaTable
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: Xml
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: VBA3Handling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Vba5Dir
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: AppleSingle
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Rpm
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: MimeEmbedLines
    type: 2
    value: 500
- type: SophosNameValue
  fields:
    name: GrpMSOffice
    type: 9
    value: 2
- type: SophosNameValue
  fields:
    name: CleanRiff
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: PeEmulator
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Bzip2
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: GrpArchiveUnpack
    type: 9
    value: 2
- type: SophosNameValue
  fields:
    name: UTF16
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: GrpSelfExtract
    type: 9
    value: 2
- type: SophosNameValue
  fields:
    name: Skip
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: VisioFileHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Vba5p
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Stuffit
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: TnefEmbedHandling
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: IgnoreTemplateBit
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Java
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Fsg
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: HqxDecompression
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Office2001Handling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Elf
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: ITSS
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: OleScriptHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: TnefAttachmentHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: CleanPng
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: PowerPointMacroHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: PowerPointEmbeddedHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: VirusDataDir
    type: 10
    value: C:\Program Files\Sophos\Sophos Anti-Virus
- type: SophosNameValue
  fields:
    name: SfxArchives
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: StorageDetOnly
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: Msi
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: StorageReport
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: WordB
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Rtf
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: FullMacroSweep
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: ZipUseChd
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: MachO
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Base64
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: OleDataMsoHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: VBA5Handling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: AllowPartialVirusData
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: MimeEmbedded
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Vbe
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: GrpExecutable
    type: 9
    value: 2
- type: SophosNameValue
  fields:
    name: FullPdf
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: SrpStreamHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Lha
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: HelpHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Upx
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: ISCabinetFull
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: GrpSuper
    type: 9
    value: 2
- type: SophosNameValue
  fields:
    name: CleanTiff
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: MSCabinet
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: CmzDecompression
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: VisioEmbedHandling
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: ISCabinet
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: GrpDisinfect
    type: 9
    value: 2
- type: SophosNameValue
  fields:
    name: CleanGif
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: OpenMacRf
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: NamespaceSupport
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: ArjDecompression
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: CleanMpeg
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Saveset
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: VirusDataName
    type: 10
    value: vdl
- type: SophosNameValue
  fields:
    name: DeleteAllMacros
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: CleanBmp
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: ExcelFormulaHandling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: LoopBackEnabled
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: RarDecompression
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: OutlookExpress
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: OLE2Handling
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: Html
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: GZipDecompression
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: UueDecompression
    type: 3
    value: 0
- type: SophosNameValue
  fields:
    name: RemoveFromSystemRestore
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: DelVBA5Project
    type: 3
    value: 1
- type: SophosNameValue
  fields:
    name: MaxIntRecDepth
    type: 2
    value: 25
- type: SophosNameValue
  fields:
    name: GrpClean
    type: 9
    value: 2
