---
name: XkmsConfig
version: 3
fields:
  URLSet:
    type: '@UrlSet'
    cardinality: 1
  name:
    type: string
    defaultValues:
    - {}
    cardinality: 1
  signingCert:
    type: '@Certificate'
    cardinality: '?'
keyFields:
- name
