---
name: EnvironmentalizedFieldString
version: 1
class: com.vordel.api.deployment.model.EnvironmentalizedFieldString
fields:
  multiline:
    type: boolean
    defaultValues:
    - data: 0
    cardinality: 1
  value:
    type: string
    defaultValues:
    - {}
    cardinality: '?'
